'use strict';

// external imports

// local imports

// constants definition
const CHILD_READY_FOR_MODULE_TRAVERSING_MESSAGE_TYPE = 'CHILD_READY_FOR_MODULE_TRAVERSING_MESSAGE_TYPE';
const CHILD_FINISH_WITH_MODULE_TRAVERSING_MESSAGE_TYPE = 'CHILD_FINISH_WITH_MODULE_TRAVERSING_MESSAGE_TYPE';
const CHILD_DELEGATE_TASK_MESSAGE_TYPE = 'CHILD_DELEGATE_TASK_MESSAGE_TYPE';

const MAX_CHILD_PROCESSES = 5;

// export
exports.CHILD_READY_FOR_MODULE_TRAVERSING_MESSAGE_TYPE = CHILD_READY_FOR_MODULE_TRAVERSING_MESSAGE_TYPE;
exports.CHILD_FINISH_WITH_MODULE_TRAVERSING_MESSAGE_TYPE = CHILD_FINISH_WITH_MODULE_TRAVERSING_MESSAGE_TYPE;
exports.CHILD_DELEGATE_TASK_MESSAGE_TYPE = CHILD_DELEGATE_TASK_MESSAGE_TYPE;
exports.MAX_CHILD_PROCESSES = MAX_CHILD_PROCESSES;
