'use strict';

// external imports

// local imports

// constants definition
const LOG_MASTER_PROCESS_TYPE = 'LOG_MASTER_PROCESS_TYPE';
const LOG_CHILD_PROCESS_TYPE = 'LOG_MASTER_PROCESS_TYPE';

const LOG_UTILITY_MESSAGE_TYPE = 'LOG_UTILITY_MESSAGE_TYPE';
const LOG_DB_MESSAGE_TYPE = 'LOG_DB_MESSAGE_TYPE';

// export
exports.LOG_MASTER_PROCESS_TYPE = LOG_MASTER_PROCESS_TYPE;
exports.LOG_CHILD_PROCESS_TYPE = LOG_CHILD_PROCESS_TYPE;

exports.LOG_UTILITY_MESSAGE_TYPE = LOG_UTILITY_MESSAGE_TYPE;
exports.LOG_DB_MESSAGE_TYPE = LOG_DB_MESSAGE_TYPE;