'use strict';

// external imports

// local imports

// constants definition
const LOG_UTILITY_MESSAGE_TYPE = 'LOG_UTILITY_MESSAGE_TYPE';
const LOG_ERROR_MESSAGE_TYPE = 'LOG_ERROR_MESSAGE_TYPE';
const LOG_DB_MESSAGE_TYPE = 'LOG_DB_MESSAGE_TYPE';
const LOG_FS_MESSAGE_TYPE = 'LOG_FS_MESSAGE_TYPE';
const LOG_TASK_MESSAGE_TYPE = 'LOG_TASK_MESSAGE_TYPE';
const LOG_REMOTE_TASK_MESSAGE_TYPE = 'LOG_REMOTE_TASK_MESSAGE_TYPE';

const MASTER_PROCESS_LOG_LABEL = ' MASTER ';
const CHILD_PROCESS_LOG_LABEL = ' CHILD ';

// export
exports.LOG_UTILITY_MESSAGE_TYPE = LOG_UTILITY_MESSAGE_TYPE;
exports.LOG_ERROR_MESSAGE_TYPE = LOG_ERROR_MESSAGE_TYPE;
exports.LOG_DB_MESSAGE_TYPE = LOG_DB_MESSAGE_TYPE;
exports.LOG_FS_MESSAGE_TYPE = LOG_FS_MESSAGE_TYPE;
exports.LOG_TASK_MESSAGE_TYPE = LOG_TASK_MESSAGE_TYPE;
exports.LOG_REMOTE_TASK_MESSAGE_TYPE = LOG_REMOTE_TASK_MESSAGE_TYPE;

exports.MASTER_PROCESS_LOG_LABEL = MASTER_PROCESS_LOG_LABEL;
exports.CHILD_PROCESS_LOG_LABEL = CHILD_PROCESS_LOG_LABEL;