'use strict';

// external imports

// local imports

// constants definition
const MASTER_SET_NAME_COMMAND_MESSAGE_TYPE = 'MASTER_SET_NAME_COMMAND_MESSAGE_TYPE';
const MASTER_SET_PATH_TO_MODULES_COMMAND_MESSAGE_TYPE = 'MASTER_SET_PATH_TO_MODULES_COMMAND_MESSAGE_TYPE';
const MASTER_DATA_MESSAGE_TYPE = 'MASTER_DATA_MESSAGE_TYPE';

// export
exports.MASTER_SET_NAME_COMMAND_MESSAGE_TYPE = MASTER_SET_NAME_COMMAND_MESSAGE_TYPE;
exports.MASTER_SET_PATH_TO_MODULES_COMMAND_MESSAGE_TYPE = MASTER_SET_PATH_TO_MODULES_COMMAND_MESSAGE_TYPE;
exports.MASTER_DATA_MESSAGE_TYPE = MASTER_DATA_MESSAGE_TYPE;