'use strict';

const OPEN_PROXY_DOMAIN_TO_FORWARD_TO = 'test2.com';
const OPEN_PROXY_FORWARD_PORT = 80;

module.exports.OPEN_PROXY_DOMAIN_TO_FORWARD_TO = OPEN_PROXY_DOMAIN_TO_FORWARD_TO;
module.exports.OPEN_PROXY_FORWARD_PORT = OPEN_PROXY_FORWARD_PORT;