'use strict';

const { cpus } = require('os');

const CHILD_SERVER_PROCESS_INITIAL_COEFFICIENT = 2.9470528301886794;
const CURRENT_NUMBER_OF_CPU_CORES = cpus().length;

const MIN_CHILD_PROCESSES = 2;
const MAX_CHILD_PROCESSES = Infinity;

const HTTP_CHILD_SERVER_TYPE = 'HTTP_CHILD_SERVER_TYPE';
const HTTPS_CHILD_SERVER_TYPE = 'HTTPS_CHILD_SERVER_TYPE';
const WEB_SOCKET_CHILD_SERVER_TYPE = 'WEB_SOCKET_CHILD_SERVER_TYPE';

module.exports.CHILD_SERVER_PROCESS_INITIAL_COEFFICIENT = CHILD_SERVER_PROCESS_INITIAL_COEFFICIENT;
module.exports.CURRENT_NUMBER_OF_CPU_CORES = CURRENT_NUMBER_OF_CPU_CORES;

module.exports.MIN_CHILD_PROCESSES = MIN_CHILD_PROCESSES;
module.exports.MAX_CHILD_PROCESSES = MAX_CHILD_PROCESSES;

module.exports.HTTP_CHILD_SERVER_TYPE = HTTP_CHILD_SERVER_TYPE;
module.exports.HTTPS_CHILD_SERVER_TYPE = HTTPS_CHILD_SERVER_TYPE;
module.exports.WEB_SOCKET_CHILD_SERVER_TYPE = WEB_SOCKET_CHILD_SERVER_TYPE;