const SERVER_PORT = 3000;

const HTML_PAGES_DIRECTORY_NAME = 'pages';
const RESOURCES_DIRECTORY_NAME = 'resources';

module.exports.SERVER_PORT = SERVER_PORT;
module.exports.HTML_PAGES_DIRECTORY_NAME = HTML_PAGES_DIRECTORY_NAME;