'use strict';

// external imports

// local imports

// implementation
const STAR_SKY_SPEED = 40;
const STAR_SKY_NUMBER_OF_STARS = 250;

const ENEMY_FREQUENCY = 1500;
const ENEMY_SHOOT_FREQUENCY = 750;
const ENEMY_MOVE_FREQUENCY = 40;
const ENEMY_SHOT_MOVE_FREQUENCY = 15;

const ENEMY_SHOOT_SPEED = 15;

// exports
export {
    STAR_SKY_SPEED,
    STAR_SKY_NUMBER_OF_STARS,

    ENEMY_FREQUENCY,
    ENEMY_SHOOT_FREQUENCY,
    ENEMY_MOVE_FREQUENCY,
    ENEMY_SHOT_MOVE_FREQUENCY,

    ENEMY_SHOOT_SPEED,
};
