const MB_PARSER_PREAMBLE_FOUND = 'MB_PARSER_PREAMBLE_FOUND';

const MB_PARSER_INITIAL_BOUNDARY_FOUND = 'MB_PARSER_INITIAL_BOUNDARY_FOUND';
const MB_PARSER_NEXT_OR_FINAL_BOUNDARY_FOUND = 'MB_PARSER_NEXT_OR_FINAL_BOUNDARY_FOUND';
const MB_PARSER_BOUNDARY_FOUND = 'MB_PARSER_BOUNDARY_FOUND';
const MB_PARSER_FINAL_BOUNDARY_FOUND = 'MB_PARSER_FINAL_BOUNDARY_FOUND';

const MB_PARSER_BOUNDARY_HEADERS_START_FOUND = 'MB_PARSER_BOUNDARY_HEADERS_START_FOUND';
const MB_PARSER_BOUNDARY_HEADERS_END_FOUND = 'MB_PARSER_BOUNDARY_HEADERS_END_FOUND';
const MB_PARSER_BOUNDARY_HEADERS_FOUND = 'MB_PARSER_BOUNDARY_HEADERS_FOUND';

const MB_PARSER_BODY_PART_FOUND = 'MB_PARSER_BODY_PART_FOUND';
const MB_PARSER_BODY_PARSED = 'MB_PARSER_BODY_PARSED';

module.exports.MB_PARSER_PREAMBLE_FOUND = MB_PARSER_PREAMBLE_FOUND;

module.exports.MB_PARSER_INITIAL_BOUNDARY_FOUND = MB_PARSER_INITIAL_BOUNDARY_FOUND;
module.exports.MB_PARSER_NEXT_OR_FINAL_BOUNDARY_FOUND = MB_PARSER_NEXT_OR_FINAL_BOUNDARY_FOUND;
module.exports.MB_PARSER_BOUNDARY_FOUND = MB_PARSER_BOUNDARY_FOUND;
module.exports.MB_PARSER_FINAL_BOUNDARY_FOUND = MB_PARSER_FINAL_BOUNDARY_FOUND;

module.exports.MB_PARSER_BOUNDARY_HEADERS_START_FOUND = MB_PARSER_BOUNDARY_HEADERS_START_FOUND;
module.exports.MB_PARSER_BOUNDARY_HEADERS_END_FOUND = MB_PARSER_BOUNDARY_HEADERS_END_FOUND;
module.exports.MB_PARSER_BOUNDARY_HEADERS_FOUND = MB_PARSER_BOUNDARY_HEADERS_FOUND;

module.exports.MB_PARSER_BODY_PART_FOUND = MB_PARSER_BODY_PART_FOUND;
module.exports.MB_PARSER_BODY_PARSED = MB_PARSER_BODY_PARSED;
