const MB_PARSER_CRLF = `\r\n`;
const MB_PARSER_HEADERS_END_INDEX = `${MB_PARSER_CRLF}${MB_PARSER_CRLF}`;

const MB_PARSER_BOUNDARY_INDEX_TEST_FUNC = (boundary) => `--${boundary}`;
const MB_PARSER_BODY_BOUNDARY_INDEX_TEST_FUNC = (boundary) => `${MB_PARSER_CRLF}${MB_PARSER_BOUNDARY_INDEX_TEST_FUNC(boundary)}`;
const MB_PARSER_FINAL_BOUNDARY_INDEX_TEST_FUNC = (boundary) => `${MB_PARSER_BODY_BOUNDARY_INDEX_TEST_FUNC(boundary)}--`;

module.exports.MB_PARSER_CRLF = MB_PARSER_CRLF;
module.exports.MB_PARSER_HEADERS_END_INDEX = MB_PARSER_HEADERS_END_INDEX;

module.exports.MB_PARSER_BOUNDARY_INDEX_TEST_FUNC = MB_PARSER_BOUNDARY_INDEX_TEST_FUNC;
module.exports.MB_PARSER_BODY_BOUNDARY_INDEX_TEST_FUNC = MB_PARSER_BODY_BOUNDARY_INDEX_TEST_FUNC;
module.exports.MB_PARSER_FINAL_BOUNDARY_INDEX_TEST_FUNC = MB_PARSER_FINAL_BOUNDARY_INDEX_TEST_FUNC;
