// external imports

// internal imports

// implementation
const MAZE_GENERATOR_NEXT_DIRECTION_UP = 'MAZE_GENERATOR_NEXT_DIRECTION_UP';
const MAZE_GENERATOR_NEXT_DIRECTION_DOWN = 'MAZE_GENERATOR_NEXT_DIRECTION_DOWN';

const MAZE_GENERATOR_NEXT_DIRECTION_LEFT = 'MAZE_GENERATOR_NEXT_DIRECTION_LEFT';
const MAZE_GENERATOR_NEXT_DIRECTION_RIGHT = 'MAZE_GENERATOR_NEXT_DIRECTION_RIGHT';

const MAZE_GENERATOR_TOP_MAZE_SIDE = 'MAZE_GENERATOR_TOP_MAZE_SIDE';
const MAZE_GENERATOR_BOTTOM_MAZE_SIDE = 'MAZE_GENERATOR_BOTTOM_MAZE_SIDE';

const MAZE_GENERATOR_LEFT_MAZE_SIDE = 'MAZE_GENERATOR_LEFT_MAZE_SIDE';
const MAZE_GENERATOR_RIGHT_MAZE_SIDE = 'MAZE_GENERATOR_RIGHT_MAZE_SIDE';

// exports
module.exports.MAZE_GENERATOR_NEXT_DIRECTION_UP = MAZE_GENERATOR_NEXT_DIRECTION_UP;
module.exports.MAZE_GENERATOR_NEXT_DIRECTION_DOWN = MAZE_GENERATOR_NEXT_DIRECTION_DOWN;

module.exports.MAZE_GENERATOR_NEXT_DIRECTION_LEFT = MAZE_GENERATOR_NEXT_DIRECTION_LEFT;
module.exports.MAZE_GENERATOR_NEXT_DIRECTION_RIGHT = MAZE_GENERATOR_NEXT_DIRECTION_RIGHT;

module.exports.MAZE_GENERATOR_TOP_MAZE_SIDE = MAZE_GENERATOR_TOP_MAZE_SIDE;
module.exports.MAZE_GENERATOR_BOTTOM_MAZE_SIDE = MAZE_GENERATOR_BOTTOM_MAZE_SIDE;

module.exports.MAZE_GENERATOR_LEFT_MAZE_SIDE = MAZE_GENERATOR_LEFT_MAZE_SIDE;
module.exports.MAZE_GENERATOR_RIGHT_MAZE_SIDE = MAZE_GENERATOR_RIGHT_MAZE_SIDE;